

package projappacademia.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Font;


/**
 *
 * @author 771900057
 */
public class janelaEsqueciSenha extends javax.swing.JFrame {
    
    /** Creates new form janelaEsqueciSenha */
    public janelaEsqueciSenha() {
        initComponents();
        if(jNewPassword.getText().equals("Digite a nova senha")){
            jNewPassword.setEchoChar((char)0);
        }
        if(jPasswordTest.getText().equals("Repita a nova senha")){
            jPasswordTest.setEchoChar((char)0);
        }
        jLabelErroSenha.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            public void paintComponent(Graphics t){

                ImageIcon im = new ImageIcon("src/fotos/fundoEsqSenha.jpg");
                Image i =im.getImage();

                t.drawImage(i,0,0, this.getSize().width,this.getSize().height,this);
            }
        };
        jTextLogin = new javax.swing.JTextField();
        jButtonConfirm = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jCheckBoxSenha = new javax.swing.JCheckBox();
        jNewPassword = new javax.swing.JPasswordField();
        jPasswordTest = new javax.swing.JPasswordField();
        jLabelErroSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextLogin.setForeground(new java.awt.Color(153, 153, 153));
        jTextLogin.setText("Digite o login");
        jTextLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextLoginFocusLost(evt);
            }
        });
        jTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLoginActionPerformed(evt);
            }
        });

        jButtonConfirm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonConfirm.setText("Confirmar");
        jButtonConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jCheckBoxSenha.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jCheckBoxSenha.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSenha.setText("mostrar senha");
        jCheckBoxSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBoxSenha.setContentAreaFilled(false);
        jCheckBoxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSenhaActionPerformed(evt);
            }
        });

        jNewPassword.setForeground(new java.awt.Color(153, 153, 153));
        jNewPassword.setText("Digite a nova senha");
        jNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNewPasswordFocusLost(evt);
            }
        });
        jNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewPasswordActionPerformed(evt);
            }
        });

        jPasswordTest.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordTest.setText("Repita a nova senha");
        jPasswordTest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordTestFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordTestFocusLost(evt);
            }
        });

        jLabelErroSenha.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabelErroSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelErroSenha.setText("*As senhas inseridas não são as mesmas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelErroSenha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordTest)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextLogin)
                            .addComponent(jNewPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSenha)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSenha))
                .addGap(18, 18, 18)
                .addComponent(jPasswordTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErroSenha)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConfirm)
                    .addComponent(jButtonVoltar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLoginActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        String login = jTextLogin.getText();
        String senha = jNewPassword.getText();
        
            
        
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jTextLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextLoginFocusGained
        if(jTextLogin.getText().equals("Digite o login")){
            jTextLogin.setText(null);
            jTextLogin.requestFocus();
            Font font = new Font("Arial", Font.PLAIN, 12);
            jTextLogin.setFont(font);
            jTextLogin.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextLoginFocusGained

    private void jTextLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextLoginFocusLost
        if(jTextLogin.getText().length()==0){
            jTextLogin.setText("Digite o login");
            Font font = new Font("Arial", Font.PLAIN, 12);
            jTextLogin.setFont(font);
            jTextLogin.setForeground(Color.GRAY);
                    
        }
    }//GEN-LAST:event_jTextLoginFocusLost

    private void jNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNewPasswordFocusGained
        if(jNewPassword.getText().equals("Digite a nova senha")){
            jNewPassword.setText(null);
            jNewPassword.requestFocus();
            jNewPassword.setEchoChar('*');
            Font font = new Font("Arial", Font.PLAIN, 12);
            jNewPassword.setFont(font);
            jNewPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jNewPasswordFocusGained

    private void jNewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNewPasswordFocusLost
        if(jNewPassword.getText().length()==0){
            jNewPassword.setText("Digite a nova senha");
            if(jNewPassword.getText().equals("Digite a nova senha")){
            jNewPassword.setEchoChar((char)0);
        }
            Font font = new Font("Arial", Font.PLAIN, 12);
            jNewPassword.setFont(font);
            jNewPassword.setForeground(Color.GRAY);
                    
        }
    }//GEN-LAST:event_jNewPasswordFocusLost

    private void jNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewPasswordActionPerformed
       
    }//GEN-LAST:event_jNewPasswordActionPerformed

    private void jCheckBoxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSenhaActionPerformed
         if(jCheckBoxSenha.isSelected()){
            jNewPassword.setEchoChar((char)0);
        }else if(!jNewPassword.getText().equals("Digite a nova senha")){
            jNewPassword.setEchoChar('*');
        }    
        
    }//GEN-LAST:event_jCheckBoxSenhaActionPerformed

    private void jPasswordTestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordTestFocusGained
        if(jPasswordTest.getText().equals("Repita a nova senha")){
            jPasswordTest.setText(null);
            jPasswordTest.requestFocus();
            jPasswordTest.setEchoChar('*');
            Font font = new Font("Arial", Font.PLAIN, 12);
            jPasswordTest.setFont(font);
            jPasswordTest.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jPasswordTestFocusGained

    private void jPasswordTestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordTestFocusLost
        if(jPasswordTest.getText().length()==0){
            jPasswordTest.setText("Repita a nova senha");
            if(jPasswordTest.getText().equals("Repita a nova senha")){
            jPasswordTest.setEchoChar((char)0);
        }
            Font font = new Font("Arial", Font.PLAIN, 12);
            jPasswordTest.setFont(font);
            jPasswordTest.setForeground(Color.GRAY);
                    
        }  
        if( !jPasswordTest.getText().equals(jNewPassword.getText()) && !jPasswordTest.getText().equals("Repita a nova senha") ){
            jLabelErroSenha.setVisible(true);
        } else {
            jLabelErroSenha.setVisible(false);
        }
    }//GEN-LAST:event_jPasswordTestFocusLost

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaEsqueciSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaEsqueciSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaEsqueciSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaEsqueciSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaEsqueciSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxSenha;
    private javax.swing.JLabel jLabelErroSenha;
    private javax.swing.JPasswordField jNewPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordTest;
    private javax.swing.JTextField jTextLogin;
    // End of variables declaration//GEN-END:variables

}
